@echo off
REM Auto-detect local IP and update mobile .env file
REM Usage: Just run this script before starting the mobile app

echo.
echo ========================================
echo  Vida Mobile - API URL Auto-Config
echo ========================================
echo.

REM Get the local IP address (IPv4 only, excluding loopback)
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4 Address"') do (
    set IP_RAW=%%a
    goto :found
)

:found
REM Trim leading spaces
for /f "tokens=* delims= " %%b in ("%IP_RAW%") do set LOCAL_IP=%%b

if "%LOCAL_IP%"=="" (
    echo [ERROR] Could not detect local IP address
    echo [INFO] Make sure you're connected to a network
    pause
    exit /b 1
)

echo [DETECTED] Your local IP: %LOCAL_IP%
echo.

REM Create the .env file with the detected IP
set API_URL=http://%LOCAL_IP%:8000

echo # Vida Mobile Environment Configuration > .env
echo # This file is auto-generated by update-api-url.bat >> .env
echo. >> .env
echo # Backend API URL (auto-detected from your local IP) >> .env
echo EXPO_PUBLIC_API_BASE_URL=%API_URL% >> .env
echo. >> .env
echo # Optional: Add other environment variables here >> .env
echo # EXPO_PUBLIC_SUPABASE_URL= >> .env
echo # EXPO_PUBLIC_SUPABASE_ANON_KEY= >> .env
echo # EXPO_PUBLIC_AMPLITUDE_KEY= >> .env

echo [SUCCESS] Updated .env file
echo [API URL] %API_URL%
echo.
echo ========================================
echo  Configuration Complete!
echo ========================================
echo.
echo Next steps:
echo   1. Make sure backend is running (docker ps)
echo   2. Start mobile app: npm start
echo   3. Scan QR code with Expo Go app
echo.
echo Your phone must be on the SAME WIFI network!
echo.
pause
