#!/usr/bin/env node
/**
 * Auto-detect local IP and update .env file.
 * Skips virtual/docker/WSL adapters so the phone can actually reach the backend.
 */

import os from "os";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const VIRTUAL_PREFIXES = [
  "docker",
  "veth",
  "br-",
  "virbr",
  "vnet",
  "vboxnet",
  "vmnet",
  "wsl",
  "hyper-v",
  "virtual",
  "tap",
  "tun",
];

function isVirtual(name) {
  const lower = name.toLowerCase();
  return VIRTUAL_PREFIXES.some((p) => lower.includes(p));
}

function getLocalIP() {
  const interfaces = os.networkInterfaces();

  // Prefer interfaces that look like real LAN adapters (Wi-Fi / Ethernet)
  const candidates = [];
  for (const [name, addrs] of Object.entries(interfaces)) {
    for (const iface of addrs) {
      if (iface.family === "IPv4" && !iface.internal && !isVirtual(name)) {
        candidates.push({ name, address: iface.address });
      }
    }
  }

  if (candidates.length === 0) return null;

  // Prefer Wi-Fi / Ethernet over anything else
  const preferred = candidates.find(
    (c) => /wi-?fi|wlan|ethernet|eth\d/.test(c.name.toLowerCase())
  );
  return preferred ? preferred.address : candidates[0].address;
}

function updateEnvFile() {
  const localIP = getLocalIP();

  if (!localIP) {
    console.error("❌ Could not detect local IP address");
    console.error("ℹ️  Make sure you're connected to a network");
    process.exit(1);
  }

  const apiUrl = `http://${localIP}:8000`;

  const envContent = `# Vida Mobile Environment Configuration
# Auto-generated by npm run start:dev

# Backend API URL (auto-detected from your local IP)
EXPO_PUBLIC_API_BASE_URL=${apiUrl}

# Optional: Add other environment variables here
# EXPO_PUBLIC_SUPABASE_URL=
# EXPO_PUBLIC_SUPABASE_ANON_KEY=
# EXPO_PUBLIC_AMPLITUDE_KEY=
`;

  const envPath = path.join(__dirname, "..", ".env");
  fs.writeFileSync(envPath, envContent, "utf8");

  console.log("✅ Environment configured");
  console.log(`📡 Local IP: ${localIP}`);
  console.log(`🔗 API URL: ${apiUrl}`);
  console.log("📱 Make sure your phone is on the same WiFi network!\n");
}

updateEnvFile();
