#!/usr/bin/env node
/**
 * Auto-detect local IP and update .env file
 * This runs automatically before starting the dev server
 */

import os from "os";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function getLocalIP() {
  const interfaces = os.networkInterfaces();

  // Try to find a non-internal IPv4 address
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      // Skip internal (loopback) and non-IPv4 addresses
      if (iface.family === "IPv4" && !iface.internal) {
        return iface.address;
      }
    }
  }

  return null;
}

function updateEnvFile() {
  const localIP = getLocalIP();

  if (!localIP) {
    console.error("❌ Could not detect local IP address");
    console.error("ℹ️  Make sure you're connected to a network");
    process.exit(1);
  }

  const apiUrl = `http://${localIP}:8000`;

  const envContent = `# Vida Mobile Environment Configuration
# Auto-generated by npm run start:dev

# Backend API URL (auto-detected from your local IP)
EXPO_PUBLIC_API_BASE_URL=${apiUrl}

# Optional: Add other environment variables here
# EXPO_PUBLIC_SUPABASE_URL=
# EXPO_PUBLIC_SUPABASE_ANON_KEY=
# EXPO_PUBLIC_AMPLITUDE_KEY=
`;

  const envPath = path.join(__dirname, "..", ".env");
  fs.writeFileSync(envPath, envContent, "utf8");

  console.log("✅ Environment configured");
  console.log(`📡 Local IP: ${localIP}`);
  console.log(`🔗 API URL: ${apiUrl}`);
  console.log("📱 Make sure your phone is on the same WiFi network!\n");
}

updateEnvFile();
